---

spring.profiles.active: develop
server.port: 9090

---
spring:
  profiles: develop
server.contextPath: /example
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?autoReconnect=true
    username: "root"
    password: "root"
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1    
spring.jpa:
    show_sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: create

---
spring:
  profiles: production
server.contextPath: /example
spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example2?autoReconnect=true
    username: "root"
    password: "root"
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1  
spring.jpa:
    show_sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update